### ISSUE TITLE
Veraltet.

### ISSUE THREAD

**Issue by Slevin7** [requileaks/requileaks.github.io#1]
Leider absolut veraltet, wann gibt es ein update?

**Comment by Metatron321** [comment]
Danke für das Backup. Sollte aber in der Tat zeitnaher stattfinden.

**Comment by Metatron321** [comment]
Mittlerweile drei Tage altes Backup. Euer Ernst?! Was soll man damit im Ernstfall denn Anfangen?

**Comment by Metatron321** [comment]
Mittlerweile drei Tage altes Backup. Euer Ernst?! Was soll man damit im Notfall denn Anfangen?

**Comment by Slevin7** [comment]
Also mal im Ernst, so ein Copy&Paste script wird doch wohl nicht so schwer sein.
Was soll denn das hier für ein Backup sein.

**Comment by requileaks** [comment]
Sind wir hier bei Wünsch-Dir-Was?
